version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
