version: '3'

services:
  postgres:
    image: 'bitnami/postgresql'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DATABASE: 'zssn'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    env_file:
      - '.env'
